### ISSUE TITLE
JSON renders differently to ELK

### ISSUE THREAD

**Issue by Baltoli** [kieler/elk-live#42]
See this [issue](https://github.com/eclipse/elk/issues/699) on the ELK repository for full info and reproduction details.

I'm not sure whether this is an issue with the elk-live rendering code or the ELKT->JSON conversion process, so I've raised an issue on both sides. Essentially, the problem is that my graph renders very differently after being converted to JSON. Is this a known issue with the visualiser?

Thanks for your help!

cc: @javierariasmoreno

**Comment by itviewer** [comment]
the reason is that ELKT backend will add defaults size information before layout https://github.com/kieler/elk-live/blob/ed64c3a2524d6d9ecc2ccd9b11458681de01e8cd/server/elkgraph-web/src/main/java/de/cau/cs/kieler/elkgraph/web/ElkGraphDiagramGenerator.xtend#L56

**Comment by mlouielu** [comment]
Add a simple recursive fix for it just like `applyDefaults`

```js
function applyDefault(graph) {
  if (graph.children) {
    for (i in graph.children) {
      c = graph.children[i];
      if (!c.width) {
        c.width = 20;
      }
      if (!c.height) {
        c.height = 20;
      }

      applyDefault(c);
    }
  }
}

var graph = {...}

applyDefault(graph)

const elk = new ELK()
elk.layout(graph)
  .then(data => ....
```
