### ISSUE TITLE
Use Without Server

### ISSUE THREAD

**Issue by saulshanabrook** [kieler/elk-live#49]
Is it possible to create a similar editor without having a backend Java server? I see that elkjs lets you do the layout client side.

**Comment by uruuru** [comment]
The [json-based](https://rtsys.informatik.uni-kiel.de/elklive/json.html) editor doesn't rely on the server, neither for layout nor for diagram generation. The corresponding code can be found [here](https://github.com/kieler/elk-live/tree/master/client/src/json).

**Comment by saulshanabrook** [comment]
Great, thanks for the pointer!

I am looking into wrapping this as a React library.

**Comment by saulshanabrook** [comment]
Have you considered publishing the client as a package on NPM to make it easier to reuse the rendering logic without having to copy all the code?

**Comment by uruuru** [comment]
Not really. The example page simply evolved over time. Publishing a clean package with minimum requirements and a proper interface requires at least a little effort :). 

Also, I'm not sure if sprotty already offers something as they frequently use ELK for layout. @spoenemann?

**Comment by saulshanabrook** [comment]
Yep, totally understand.

I was thinking that over just using ELK, Sprotty offers an actual engine to materialize the graph on the page, as a replacement for something like cytoscapejs

**Comment by uruuru** [comment]
FYI, there's been a discussion a while back regarding simple rendering: https://github.com/kieler/elkjs/issues/85. Unfortunately, I've never found the time to look at it in further detail.

**Comment by saulshanabrook** [comment]
Thanks for the pointer! I noticed that in the JSON editor, you have to put in the width and height explicitly for the nodes. However, with the elkt you don't. Do you know if it's possible to use the JS only code to automatically compute the widths and height based on the size of the node (the labels, etc)?

**Comment by uruuru** [comment]
Slightly off-topic to the issue:
* Explanation in https://github.com/eclipse/elk/issues/699 and #42
* The option `nodeSize.constraints` may help with automatic sizing. I mention it in 699.

**Comment by saulshanabrook** [comment]
Thanks for the pointers!

In trying to figure out how to get the browser based only method to generate node sizes, I also found [https://github.com/kieler/elkjs/issues/128#issuecomment-808486375](https://github.com/kieler/elkjs/issues/128#issuecomment-808486375) where you say:

> In case you looked at the layouts of the elkt version of elk live, there the rendering part actually estimates the text dimensions using browser facilities.

Could you point me to where it does this estimation to see if I could use it with the code in the current JSON viewer to automatically try to size the nodes based on their label sizes?

**Comment by uruuru** [comment]
Not off the top of my head as that happens somewhere in sprotty.

**Comment by spoenemann** [comment]
Not sure whether that's what you're looking for, but we have https://www.npmjs.com/package/sprotty-elk
